### ISSUE TITLE
netpbm not found on my Ubuntu 18.04

### ISSUE THREAD

**Issue by ciampix** [brouhaha/tumble#1]
make
bison -d -v parser.y
make: bison: Command not found
flex  -t scanner.l > scanner.c
/bin/sh: 1: flex: not found
cc   g4_table_gen.o  -ltiff -ljpeg -lnetpbm -lz -lm -o g4_table_gen
/usr/bin/ld: impossibile trovare -lnetpbm
collect2: error: ld returned 1 exit status
cc   bitblt_table_gen.o  -ltiff -ljpeg -lnetpbm -lz -lm -o bitblt_table_gen
/usr/bin/ld: impossibile trovare -lnetpbm
collect2: error: ld returned 1 exit status
rm scanner.c

but apparently netpbm IS installed:

dpkg  -l|grep netpbm
ii  libnetpbm9                                                       2:10.0-15.3build1                            amd64        Shared libraries for netpbm (v9)
ii  libnetpbm9-dev                                                   2:10.0-15.3build1                            amd64        Development libraries and header files (v9)
ii  netpbm                                                           2:10.0-15.3build1                            amd64        Graphics conversion tools between image formats

TIA

**Comment by philpem** [comment]
Your bigger problem is not having bison and flex installed. The config parser and lexer won't be built, which will prevent anything from being linked at the end.

On an ubuntu system you need to do:

```
sudo apt install flex bison libnetpbm10-dev
```

Debian based distros use a different version of libnetpbm which is a bit strange. I've put together a fix for this mess and am in the process of submitting a patch.

**Comment by brouhaha** [comment]
The netpbm path patch has been merged.
