### ISSUE TITLE
Clarification on big-endian compatibility

### ISSUE THREAD

**Issue by pkubaj** [brouhaha/tumble#11]
In your README you state that tumble is only little-endian compatible.
However, in https://github.com/brouhaha/tumble/blob/master/bitblt_table_gen.c#L73 there is clearly mention about big-endian support.
Is tumble after all supported on big-endian?

**Comment by brouhaha** [comment]
I don't have any big-endian machine that I can conveniently test on, so I'm not entirely certain what the status of big-endian support is.

If there's still any issue with big-endian, it is likely only with writing bilevel images using group 4 fax compression.

**Comment by pkubaj** [comment]
OK, then I guess that statement about incompatibility can be safely dropped (I successfully tested on big-endian machine).

**Comment by brouhaha** [comment]
Dropped claim of big-endian being unsupportted from README.
