### ISSUE TITLE
Tiff does not work in a portable way (breaks in OpenBSD)

### ISSUE THREAD

**Issue by marcespie** [brouhaha/tumble#2]
The header check in open_fill_input_file  is broken. It assumes rewind will rewind both the FILE* and the fd, and it does not.

I propose getting rid of it entirely, as TIFFFdOpen  will check headers by itself.

Baring that, you should instead lseek(fileno(f), 0, SEEK_SET);

I assume you never look at the FILE* again ?

**Comment by brouhaha** [comment]
Your assumption is correct. open_tiff_input_file() is the only place that uses fileno(), except one that's generated by bison that isn't at issue here. It's kind of a crock that libtiff won't work with C streams. Anyhow, I think you're right that an lseek would fix this, so I've added that add that, along with recover if TIFFFdOpen() fails and another input handler gets called on the C stdio stream. If that doesn't fix it, you can reopen this bug or open a new one.
